### ISSUE TITLE
player continues on closure of linux GTK embedder

### ISSUE THREAD

**Issue by jwinarske** [bleonard252/just_audio_mpv#14]
Player should be destroyed on exit.

**Comment by bleonard252** [comment]
Unfortunately, it's not possible to destroy anything on exit from the plugin. MPV is an external process, which Flutter doesn't kill it when it exits, and the plugin is not offered any sort of "before-the-program-exits" hook to use.

This will have to be worked around in the app by using something like [`window_manager`](https://pub.dev/packages/window_manager#quit-on-close) to tell the player to stop when the app closes.

**Comment by jwinarske** [comment]
In the case of Linux when you spawn a process you can store the process id, which you can use later to issue `kill -9 <pid>`.  It's a minor implementation detail.
